name 'settings-windows'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures settings-windows'
long_description 'Installs/Configures settings-windows'
version '0.1.0'
